# Generated by Django 6.1.1 on 2026-09-10 11:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms_backendapp', '0001_initial'),
        ('cms_doctorapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabTestResult',
            fields=[
                ('result_id', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('result_date', models.DateField()),
                ('result_data', models.TextField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('performed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lab_results_performed', to='cms_backendapp.staff')),
                ('test', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='cms_doctorapp.labtest')),
            ],
            options={
                'db_table': 'lab_test_results',
                'indexes': [models.Index(fields=['performed_by'], name='lab_test_re_perform_1a4f5d_idx')],
            },
        ),
    ]
