# Generated by Django 6.1.1 on 2026-09-10 11:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms_backendapp', '0001_initial'),
        ('cms_doctorapp', '0001_initial'),
        ('cms_pharmapp', '0001_initial'),
        ('cms_recepapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultationrecord',
            name='appointment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultation_records', to='cms_recepapp.appointment'),
        ),
        migrations.AddField(
            model_name='consultationrecord',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consultation_records', to='cms_recepapp.patient'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctors', to='cms_backendapp.department'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='staff',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='doctor_profile', to='cms_backendapp.staff'),
        ),
        migrations.AddField(
            model_name='consultationrecord',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consultation_records', to='cms_doctorapp.doctor'),
        ),
        migrations.AddField(
            model_name='labtest',
            name='appointment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_tests', to='cms_recepapp.appointment'),
        ),
        migrations.AddField(
            model_name='labtest',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lab_tests_ordered', to='cms_doctorapp.doctor'),
        ),
        migrations.AddField(
            model_name='labtest',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lab_tests', to='cms_recepapp.patient'),
        ),
        migrations.AddField(
            model_name='labtest',
            name='test_catalog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lab_tests', to='cms_backendapp.labtestcatalog'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='appointment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescriptions', to='cms_recepapp.appointment'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prescriptions', to='cms_doctorapp.doctor'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prescriptions', to='cms_recepapp.patient'),
        ),
        migrations.AddField(
            model_name='prescriptionitem',
            name='medicine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prescription_items', to='cms_pharmapp.medicine'),
        ),
        migrations.AddField(
            model_name='prescriptionitem',
            name='prescription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='cms_doctorapp.prescription'),
        ),
        migrations.AddIndex(
            model_name='doctor',
            index=models.Index(fields=['department'], name='doctors_departm_aa01a5_idx'),
        ),
        migrations.AddIndex(
            model_name='consultationrecord',
            index=models.Index(fields=['patient'], name='consultatio_patient_f5352b_idx'),
        ),
        migrations.AddIndex(
            model_name='consultationrecord',
            index=models.Index(fields=['doctor'], name='consultatio_doctor__1475cd_idx'),
        ),
        migrations.AddIndex(
            model_name='labtest',
            index=models.Index(fields=['status'], name='lab_tests_status_a1f2b5_idx'),
        ),
        migrations.AddIndex(
            model_name='labtest',
            index=models.Index(fields=['doctor'], name='lab_tests_doctor__e700af_idx'),
        ),
        migrations.AddIndex(
            model_name='labtest',
            index=models.Index(fields=['patient'], name='lab_tests_patient_6ecb32_idx'),
        ),
        migrations.AddIndex(
            model_name='prescription',
            index=models.Index(fields=['patient'], name='prescriptio_patient_408a4b_idx'),
        ),
        migrations.AddIndex(
            model_name='prescription',
            index=models.Index(fields=['status'], name='prescriptio_status_1d7db8_idx'),
        ),
        migrations.AddIndex(
            model_name='prescriptionitem',
            index=models.Index(fields=['prescription'], name='prescriptio_prescri_61055d_idx'),
        ),
        migrations.AddIndex(
            model_name='prescriptionitem',
            index=models.Index(fields=['medicine'], name='prescriptio_medicin_38e531_idx'),
        ),
    ]
